apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: guacamole
  namespace: guacamole
spec:
  selector:
    matchLabels:
      app: guacamole
  replicas: 1
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
        - name: guacamole
          image: guacamole/guacamole
          envFrom:
            - configMapRef:
                name: guacamole
            - secretRef:
                name: guacamole-common-db
          volumeMounts:
            - name: guacamole
              mountPath: /guacamole
  volumeClaimTemplates:
    - metadata:
        name: guacamole
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: guacamole
spec:
  type: LoadBalancer
  ports:
    - name: guacamole
      port: 8080
      targetPort: 8080
  selector:
    app: guacamole
